### ISSUE TITLE
Difficulty on import

### ISSUE THREAD

**Issue by biojerm** [MITHaystack/scikit-dataaccess#2]
I am having trouble importing scikit-dataaccess and was wondering if anyone had any suggestions.

I am trying to replicate one of the examples but am having trouble with imports this is the code I copied from [here](https://github.com/MITHaystack/scikit-dataaccess/blob/master/skdaccess/examples/Demo_PBO.ipynb).  I have also tried a few other examples but they all give me the same error.

```
from skdaccess.geo.pbo import DataFetcher as PBO_DF
from skdaccess.framework.param_class import *
```

This is the error I get:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-42ef5642d932> in <module>()
----> 1 from skdaccess.geo.pbo import DataFetcher as PBO_DF
      2 from skdaccess.framework.param_class import *

c:\users\splab-pc\anaconda3\envs\py3k\lib\site-packages\skdaccess\geo\pbo\__init__.py in <module>()
----> 1 from .data_fetcher import DataFetcher

c:\users\splab-pc\anaconda3\envs\py3k\lib\site-packages\skdaccess\geo\pbo\data_fetcher.py in <module>()
     28 
     29 # mithagi required Base,Utils imports
---> 30 from skdaccess.framework.data_class import DataFetcherStorage, TableWrapper
     31 from skdaccess.utilities import pbo_util
     32 

c:\users\splab-pc\anaconda3\envs\py3k\lib\site-packages\skdaccess\framework\data_class.py in <module>()
     41 from io import BytesIO
     42 from http.cookiejar import CookieJar
---> 43 import fcntl
     44 import struct
     45 

ModuleNotFoundError: No module named 'fcntl'

```

From the first few Google results it looks like `fcntl` is a Linux thing with no easy Windows 10 option.  At the moment I am working on a Windows 10 computer, and was wondering if anyone had suggestions on the best way for me to proceed?  I saw version 1.1 added Windows support, I just don't know if only some modules support Windows or if in theory they all should.

**Comment by CodyRude** [comment]
Some file locking was added to help prevent two processes writing to the same file. This file locking method isn't available on Windows, so the current version of the software only works on Linux or OS X.

**Comment by biojerm** [comment]
Thanks for the follow up,  I will try again with my ubuntu box.
